### PR TITLE
General patches and code clean-up

### LINKED ISSUE #13: CLI failing to start
The login steps on the README don't seem to be working. Running `paystack` after installing the CLI throws an exception.

```
root@830cfa0ee265:/# paystack
paystack $ 

node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module './paystack/apis'
Require stack:
- /usr/local/lib/node_modules/@paystack-oss/dev-cli/lib/helpers.js
- /usr/local/lib/node_modules/@paystack-oss/dev-cli/commands/webhook.js
- /usr/local/lib/node_modules/@paystack-oss/dev-cli/cli.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@paystack-oss/dev-cli/lib/helpers.js:4:14)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/lib/node_modules/@paystack-oss/dev-cli/lib/helpers.js',
    '/usr/local/lib/node_modules/@paystack-oss/dev-cli/commands/webhook.js',
    '/usr/local/lib/node_modules/@paystack-oss/dev-cli/cli.js'
  ]
}

```

Steps to replicate using docker (also breaks outside of docker):
```bash
docker run -ti node:lts bash
npm install -g @paystack-oss/dev-cli
paystack
```

### LINKED ISSUE #20: Undefined error when logging in
This one is quite simple. It does not let me log in. 

```powershell
npx paystack login
Debugger attached.
Debugger attached.
Email address
myactualemail@gmail.com
Password
***************
Logging in
Unable to sign in, please try again in a few minutes
    Error: LOGIN ERROR: undefined
Waiting for the debugger to disconnect...
Waiting for the debugger to disconnect...
```

### PR DESCRIPTION
**Pull request by Tobshub**
## Changes: 
- Removed `.DS_Store` and added it to `.gitignore`
- Added a `.prettierrc` file for consistent formatting and ran prettier on all the files
- Removed `package.json.preferGlobal` option (deprecated as per [here](https://docs.npmjs.com/cli/v6/configuring-npm/package-json#preferglobal))
- Renamed `./lib/Paystack` to `./lib/paystack` (fixes #13)
- Converted files from commonjs modules to ES modules
- Converted all uses of `global` to `globalThis` (legacy as per [here](https://nodejs.org/api/globals.html#global))
- Fixed function to remove duplicate logic and correctly detect when user is already logged in
- Fixed logging `undefined` as an error (fixes #20)

### CODE REVIEW

**Comment by Tobshub** [comment]
I promise it's not a large PR, just the formatting and removing the .DS_Store :joy:

**Review by lucian-duta — APPROVED** [review]
**Review Feedback:**

1. **.DS_Store & .gitignore**: Excellent initiative in removing system-specific files and ensuring they're not committed in the future.
   
2. **.prettierrc**: A thoughtful addition for ensuring consistent code formatting across the project.
   
3. **package.json.preferGlobal**: Kudos for staying updated with the latest standards and eliminating deprecated options.
   
4. **Renamed ./lib/Paystack**: This is a valuable fix, especially considering it resolves a known issue (#13) with the CLI.

5. **Module Conversions**: Transitioning from commonjs to ES modules aligns well with modern JavaScript practices. Great move!

6. **global to globalThis**: It's good to see proactive steps for legacy support.

7. **Duplicate Logic**: Streamlining code by eliminating repetitive logic always improves maintainability. Well done!

8. **Logging Issue**: Addressing the "Undefined error" issue (#20) is crucial for clarity during debugging sessions. Thanks for spotting and fixing it.

**Overall Feedback:**

These changes look impressive and seem to significantly enhance the project's code quality. Even though I don't have approval rights on this repository, if I did, I'd certainly give it a thumbs up. Great work!

**Review by tolu-paystack — APPROVED** [review]
LGTM

**Comment by tolu-paystack** [comment]
@lukman-paystack can you merge please? I've reviewed the changes and we're good to go

**Review by lukman-paystack — APPROVED** [review]

**Pull request merged**
